name: Polenta
version: 1.3.1
date: 01/06/2012
description: Polycyclic presentations for matrix groups

authors:
    - name: Bjoern Assmann
      url: http://www.cs.st-andrews.ac.uk/~bjoern/

maintainers:
    - name: Max Horn
      url: http://www.icm.tu-bs.de/~mhorn

GAP: ">= 4.4"

needed-pkgs:
    - name: "polycyclic"
      version: "2.10.1"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/polycyclic/"
    - name: "alnuth"
      version: "2.2.3"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/Alnuth/"
    - name: "radiroot"
      version: "2.4"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/radiroot/"

suggested-pkgs:
    - name: "aclib"
      version: "1.0"
      url: "http://www.icm.tu-bs.de/~beick/so.html"

www: http://www.icm.tu-bs.de/ag_algebra/software/Polenta/
readme: http://www.icm.tu-bs.de/ag_algebra/software/Polenta/README
packageinfo: http://www.icm.tu-bs.de/ag_algebra/software/Polenta/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www.icm.tu-bs.de/ag_algebra/software/Polenta/polenta-1.3.1.tar.gz
    - name: .tar.bz2
      url: http://www.icm.tu-bs.de/ag_algebra/software/Polenta/polenta-1.3.1.tar.bz2

abstract: The <span class="pkgname">Polenta</span> package provides  methods to compute polycyclic presentations of matrix groups (finite or infinite). As a by-product, this package gives some functionality to compute certain module series for modules of solvable groups. For example, if G is a rational polycyclic matrix group, then we can compute the radical series of the natural Q[G]-module Q^d.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
